TGL-RVP: add definitions for RT711 (SDW) and RT1308 (SDW)
thesofproject/acpi-scripts pull request #7
Opened 2020-03-04 05:16 UTC by RanderWang

RT711 is on link0 and two RT1308s on link1

2020-03-04 05:17 UTC, RanderWang commented
@plbossart  There is acpi table for two sdw 1308s.

2020-03-04 10:01 UTC, lgirdwood commented
@RanderWang can you fix the conflicts. Thanks

2020-03-04 16:05 UTC, plbossart requested changes
typo below?

Also I am not sure why we have conflicts, but you may want to call this rtk_sdw_711_1308 and have a different file for the rtk_sdw_711_i2s_1308 case?

2020-03-04 16:05 UTC, plbossart commented on TGL-RVP/rtk_sdw_link.asl
> +        Device (RTK0) // RT711 on link1
link0?

2020-03-04 22:11 UTC, plbossart commented
TGL-RVP/rtk_sdw_link.asl     20:   "RTKSDWTabl",
Error    6155 -         Invalid OEM Table ID ^  (Length cannot exceed 8 characters)

2020-03-05 01:41 UTC, RanderWang commented
> TGL-RVP/rtk_sdw_link.asl 20: "RTKSDWTabl",
> Error 6155 - Invalid OEM Table ID ^ (Length cannot exceed 8 characters)

I validated it on my TGL-U, I don't know why it doesn't work on TGL-Y

2020-03-05 12:57 UTC, plbossart commented
> > TGL-RVP/rtk_sdw_link.asl 20: "RTKSDWTabl",
> > Error 6155 - Invalid OEM Table ID ^ (Length cannot exceed 8 characters)
> 
> I validated it on my TGL-U, I don't know why it doesn't work on TGL-Y

the error happens during the .aml file generation, so it's possible that you are using different acpica-tools. it's not related to the hardware proper. I called it RSDWTABL and things worked fine.

2020-03-05 12:57 UTC, plbossart approved these changes

2020-03-05 12:57 UTC, merged